// This file is generated by shadcn. You can edit the file, but don't rename it as
// a lot of generated shadcn components reference this file.

import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
